import mods.gregtech.multiblock.Builder;
import mods.gregtech.multiblock.FactoryBlockPattern;
import mods.gregtech.multiblock.RelativeDirection;
import mods.gregtech.multiblock.functions.IPatternBuilderFunction;
import mods.gregtech.IControllerTile;
import mods.gregtech.multiblock.CTPredicate;
import mods.gregtech.multiblock.IBlockPattern;
import mods.gregtech.recipe.FactoryRecipeMap;
import mods.gregtech.recipe.RecipeMap;
import mods.gregtech.recipe.functions.IRunOverclockingLogicFunction;
import mods.gregtech.recipe.IRecipeLogic;
import mods.gregtech.recipe.IRecipe;
 
global nanoswarm_hives as RecipeMap = FactoryRecipeMap.start("nanoswarm_hives")
    .maxInputs(6)
    .maxFluidInputs(3)
	.maxFluidOutputs(6)
	.maxOutputs(3)
    .build();
 
Builder.start("nanoswarm_hives", 32046)
    .withPattern(function(controller as IControllerTile) as IBlockPattern {
        return FactoryBlockPattern.start()
            .aisle(
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "   A   ",
        "   B   ",
        "   B   ",
        "   B   ",
        "   B   ",
        "   B   ",
        "   B   ",
        "   A   ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       "
      )
      .aisle(
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       "
      )
      .aisle(
        "       ",
        "       ",
        "       ",
        "       ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        " CABAC ",
        " CABAC ",
        " CABAC ",
        " CABAC ",
        " BB BB ",
        " BB BB ",
        " BB BB ",
        " BB BB ",
        " BB BB ",
        " BB BB ",
        " BB BB ",
        " BB BB ",
        " CABAC ",
        " CABAC ",
        " CABAC ",
        " CABAC ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "       ",
        "       ",
        "       ",
        "       "
      )
      .aisle(
        "       ",
        "   B   ",
        "   B   ",
        "   B   ",
        "  BBB  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        " BB BB ",
        " BB BB ",
        " B   B ",
        " B   B ",
        " B   B ",
        "BB   BB",
        "BB   BB",
        " B   B ",
        " B   B ",
        " B   B ",
        " BB BB ",
        " BB BB ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  BBB  ",
        "   B   ",
        "   B   ",
        "   B   ",
        "       "
      )
      .aisle(
        "   X   ",
        "   B   ",
        "   B   ",
        "  BBB  ",
        "  BBB  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        " BB BB ",
        " B   B ",
        " B   B ",
        " B   B ",
        " B   B ",
        "BB   BB",
        "BB   BB",
        " B   B ",
        " B   B ",
        " B   B ",
        " B   B ",
        " BB BB ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  BBB  ",
        "  BBB  ",
        "   B   ",
        "   B   ",
        "   B   "
      )
      .aisle(
        "   B   ",
        "   B   ",
        "   B   ",
        "  BBB  ",
        "  BBB  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        " BB BB ",
        " B   B ",
        " B   B ",
        " B   B ",
        " B   B ",
        "BB   BB",
        "BB   BB",
        " B   B ",
        " B   B ",
        " B   B ",
        " B   B ",
        " BB BB ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  BBB  ",
        "  BBB  ",
        "   B   ",
        "   B   ",
        "   B   "
      )
      .aisle(
        "       ",
        "   B   ",
        "   B   ",
        "   B   ",
        "  BBB  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        " BB BB ",
        " BB BB ",
        " B   B ",
        " B   B ",
        " B   B ",
        "BB   BB",
        "BB   BB",
        " B   B ",
        " B   B ",
        " B   B ",
        " BB BB ",
        " BB BB ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  B B  ",
        "  BBB  ",
        "   B   ",
        "   B   ",
        "   B   ",
        "       "
      )
      .aisle(
        "       ",
        "       ",
        "       ",
        "       ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        " CABAC ",
        " CABAC ",
        " CABAC ",
        " CABAC ",
        " BB BB ",
        " BB BB ",
        " BB BB ",
        " BB BB ",
        " BB BB ",
        " BB BB ",
        " BB BB ",
        " BB BB ",
        " CABAC ",
        " CABAC ",
        " CABAC ",
        " CABAC ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "       ",
        "       ",
        "       ",
        "       "
      )
      .aisle(
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "  CBC  ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       "
      )
      .aisle(
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "   A   ",
        "   B   ",
        "   B   ",
        "   B   ",
        "   B   ",
        "   B   ",
        "   B   ",
        "   A   ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       "
      )
            .where("X", controller.self())
			.where("C", <metastate:gregtech:meta_block_frame_7:15>)
			.where("A", <metastate:gregtech:black_lamp:0>)
            .where("B", CTPredicate.states(<metastate:contenttweaker:naq_housing:0>)
                | CTPredicate.abilities(<mte_ability:MAINTENANCE_HATCH>).setMinGlobalLimited(1).setMaxGlobalLimited(1).setPreviewCount(1)
                | CTPredicate.abilities(<mte_ability:MUFFLER_HATCH>).setMinGlobalLimited(1).setMaxGlobalLimited(1).setPreviewCount(1)
                | CTPredicate.abilities(<mte_ability:IMPORT_ITEMS>).setMinGlobalLimited(1).setMaxGlobalLimited(1).setPreviewCount(1)
                | CTPredicate.abilities(<mte_ability:IMPORT_FLUIDS>).setMinGlobalLimited(1).setMaxGlobalLimited(1).setPreviewCount(1)
			    | CTPredicate.abilities(<mte_ability:EXPORT_ITEMS>).setMinGlobalLimited(1).setMaxGlobalLimited(1).setPreviewCount(1)
			    | CTPredicate.abilities(<mte_ability:EXPORT_FLUIDS>).setMinGlobalLimited(1).setMaxGlobalLimited(1).setPreviewCount(1)
                | CTPredicate.abilities(<mte_ability:INPUT_ENERGY>).setMinGlobalLimited(1).setMaxGlobalLimited(2).setPreviewCount(1)
            )
            .where(" ",CTPredicate.getAny())
        .build();
    } as IPatternBuilderFunction)
    .withRecipeMap(nanoswarm_hives)
    .withBaseTexture(<metastate:contenttweaker:naq_housing:0>)
    .buildAndRegister();
nanoswarm_hives.recipeBuilder()
    .duration(1000)  
    .EUt(10000000)  
    .inputs(<ore:blockCoal>*64,<gregtech:meta_item_1:599>*64) 
	.notConsumable(<ore:craftingLensBlack>)
	.fluidInputs(<liquid:uu_matter>*160000)
	.outputs(<contenttweaker:nanites>*64)
    .buildAndRegister(); 