mods.gregtech.cutter.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_meta_item_1', 83))
	.fluidInputs(fluid('lubricant')*1000)
    .outputs(item('appliedenergistics2:material', 18)*16)
    .duration(200) 
    .EUt(1960) 
    .buildAndRegister()
	
mods.gregtech.cutter.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_meta_item_1', 84))
	.fluidInputs(fluid('lubricant')*1000)
    .outputs(item('appliedenergistics2:material', 16)*16)
    .duration(200) 
    .EUt(1960) 
    .buildAndRegister()
	
mods.gregtech.cutter.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_meta_item_1', 85))
	.fluidInputs(fluid('lubricant')*1000)
    .outputs(item('appliedenergistics2:material', 17)*16)
    .duration(200) 
    .EUt(1960) 
    .buildAndRegister()
	
	
mods.gregtech.assembler.recipeBuilder()
    .inputs(item('appliedenergistics2:material', 17),item('gregtech:meta_gear', 2517),item('gregtech:meta_plate', 20051),item('gregtech:meta_item_1', 523),item('gregtech:meta_item_1', 524),item('gregtech:meta_item_1', 525))
	.fluidInputs(fluid('lubricant')*1000)
    .outputs(item('appliedenergistics2:material', 24)*4)
    .duration(200) 
    .EUt(1960) 
    .buildAndRegister()
	
mods.gregtech.assembler.recipeBuilder()
    .inputs(item('appliedenergistics2:material', 17),item('gregtech:meta_gear', 2517),item('gregtech:meta_plate', 20051),item('gregtech:meta_item_1', 528),item('gregtech:meta_item_1', 529),item('gregtech:meta_item_1', 530))
	.fluidInputs(fluid('lubricant')*1000)
    .outputs(item('appliedenergistics2:material', 24)*8)
    .duration(200) 
    .EUt(1960) 
    .buildAndRegister()
	
mods.gregtech.assembler.recipeBuilder()
    .inputs(item('appliedenergistics2:material', 17),item('gregtech:meta_gear', 2517),item('gregtech:meta_plate', 20051),item('gcys:meta_item_1', 423),item('gcys:meta_item_1', 422),item('gcys:meta_item_1', 420))
	.fluidInputs(fluid('lubricant')*1000)
    .outputs(item('appliedenergistics2:material', 24)*32)
    .duration(200) 
    .EUt(1960) 
    .buildAndRegister()
	
mods.gregtech.assembler.recipeBuilder()
    .inputs(item('appliedenergistics2:material', 17),item('gregtech:meta_gear', 2517),item('gregtech:meta_plate', 20051),item('gcys:meta_item_1', 428),item('gcys:meta_item_1', 427),item('gcys:meta_item_1', 425))
	.fluidInputs(fluid('lubricant')*1000)
    .outputs(item('appliedenergistics2:material', 24)*64)
    .duration(200) 
    .EUt(1960) 
    .buildAndRegister()
	
	
mods.gregtech.assembler.recipeBuilder()
    .inputs(item('appliedenergistics2:material', 16),item('gregtech:meta_gear', 2517),item('gregtech:meta_plate', 20051),item('gregtech:meta_item_1', 523),item('gregtech:meta_item_1', 524),item('gregtech:meta_item_1', 525))
	.fluidInputs(fluid('lubricant')*1000)
    .outputs(item('appliedenergistics2:material', 23)*4)
    .duration(200) 
    .EUt(1960) 
    .buildAndRegister()
	
mods.gregtech.assembler.recipeBuilder()
    .inputs(item('appliedenergistics2:material', 16),item('gregtech:meta_gear', 2517),item('gregtech:meta_plate', 20051),item('gregtech:meta_item_1', 528),item('gregtech:meta_item_1', 529),item('gregtech:meta_item_1', 530))
	.fluidInputs(fluid('lubricant')*1000)
    .outputs(item('appliedenergistics2:material', 23)*8)
    .duration(200) 
    .EUt(1960) 
    .buildAndRegister()
	
mods.gregtech.assembler.recipeBuilder()
    .inputs(item('appliedenergistics2:material', 16),item('gregtech:meta_gear', 2517),item('gregtech:meta_plate', 20051),item('gcys:meta_item_1', 423),item('gcys:meta_item_1', 422),item('gcys:meta_item_1', 420))
	.fluidInputs(fluid('lubricant')*1000)
    .outputs(item('appliedenergistics2:material', 23)*32)
    .duration(200) 
    .EUt(1960) 
    .buildAndRegister()
	
mods.gregtech.assembler.recipeBuilder()
    .inputs(item('appliedenergistics2:material', 16),item('gregtech:meta_gear', 2517),item('gregtech:meta_plate', 20051),item('gcys:meta_item_1', 428),item('gcys:meta_item_1', 427),item('gcys:meta_item_1', 425))
	.fluidInputs(fluid('lubricant')*1000)
    .outputs(item('appliedenergistics2:material', 23)*64)
    .duration(200) 
    .EUt(1960) 
    .buildAndRegister()
	
	
	
mods.gregtech.assembler.recipeBuilder()
    .inputs(item('appliedenergistics2:material', 18),item('gregtech:meta_gear', 2517),item('gregtech:meta_plate', 20051),item('gregtech:meta_item_1', 523),item('gregtech:meta_item_1', 524),item('gregtech:meta_item_1', 525))
	.fluidInputs(fluid('lubricant')*1000)
    .outputs(item('appliedenergistics2:material', 22)*4)
    .duration(200) 
    .EUt(1960) 
    .buildAndRegister()
	
mods.gregtech.assembler.recipeBuilder()
    .inputs(item('appliedenergistics2:material', 18),item('gregtech:meta_gear', 2517),item('gregtech:meta_plate', 20051),item('gregtech:meta_item_1', 528),item('gregtech:meta_item_1', 529),item('gregtech:meta_item_1', 530))
	.fluidInputs(fluid('lubricant')*1000)
    .outputs(item('appliedenergistics2:material', 22)*8)
    .duration(200) 
    .EUt(1960) 
    .buildAndRegister()
	
mods.gregtech.assembler.recipeBuilder()
    .inputs(item('appliedenergistics2:material', 18),item('gregtech:meta_gear', 2517),item('gregtech:meta_plate', 20051),item('gcys:meta_item_1', 423),item('gcys:meta_item_1', 422),item('gcys:meta_item_1', 420))
	.fluidInputs(fluid('lubricant')*1000)
    .outputs(item('appliedenergistics2:material', 22)*32)
    .duration(200) 
    .EUt(1960) 
    .buildAndRegister()
	
mods.gregtech.assembler.recipeBuilder()
    .inputs(item('appliedenergistics2:material', 18),item('gregtech:meta_gear', 2517),item('gregtech:meta_plate', 20051),item('gcys:meta_item_1', 428),item('gcys:meta_item_1', 427),item('gcys:meta_item_1', 425))
	.fluidInputs(fluid('lubricant')*1000)
    .outputs(item('appliedenergistics2:material', 22)*64)
    .duration(200) 
    .EUt(1960) 
    .buildAndRegister()