//AE2 物品全面TC化

//石英纤维
crafting.removeByOutput(item('appliedenergistics2:part', 140))
mods.gregtech.assembler.recipeBuilder()
    .inputs(ore('paneGlass') * 6)
    .inputs(metaitem('dustNetherQuartz') * 3)
    .outputs(item('appliedenergistics2:part', 140) * 4)
    .duration(100)
    .EUt(16)
    .buildAndRegister()

mods.gregtech.assembler.recipeBuilder()
    .inputs(ore('paneGlass') * 6)
    .inputs(metaitem('dustCertusQuartz') * 3)
    .outputs(item('appliedenergistics2:part', 140) * 8)
    .duration(100)
    .EUt(16)
    .buildAndRegister()

mods.gregtech.assembler.recipeBuilder()
    .inputs(ore('paneGlass') * 6)
    .inputs(metaitem('dustNetherQuartz') * 3)
    .inputs(ore('wireFineBorosilicateGlass') * 8)
    .circuitMeta(1)
    .outputs(item('appliedenergistics2:part', 140) * 8)
    .duration(100)
    .EUt(64)
    .buildAndRegister()

mods.gregtech.assembler.recipeBuilder()
    .inputs(ore('paneGlass') * 6)
    .inputs(metaitem('dustCertusQuartz') * 3)
    .inputs(ore('wireFineBorosilicateGlass') * 8)
    .circuitMeta(1)
    .outputs(item('appliedenergistics2:part', 140) * 16)
    .duration(100)
    .EUt(64)
    .buildAndRegister()

//石英玻璃
crafting.removeByOutput(item('appliedenergistics2:quartz_glass') * 4)
mods.gregtech.electric_blast_furnace.recipeBuilder()
    .inputs(ore('blockGlass') * 4)
    .inputs(metaitem('dustCertusQuartz') * 1)
    .outputs(item('appliedenergistics2:quartz_glass') * 8)
    .duration(100)
    .property("temperature", 1800)
    .EUt(120)
    .buildAndRegister()
mods.gregtech.electric_blast_furnace.recipeBuilder()
    .inputs(ore('blockGlass') * 4)
    .inputs(metaitem('dustNetherQuartz') * 1)
    .outputs(item('appliedenergistics2:quartz_glass') * 8)
    .duration(100)
    .property("temperature", 1800)
    .EUt(120)
    .buildAndRegister()

//聚能石英玻璃
crafting.removeByOutput(item('appliedenergistics2:quartz_vibrant_glass'))
mods.gregtech.electric_blast_furnace.recipeBuilder()
    .inputs(item('appliedenergistics2:quartz_glass') * 1)
    .inputs(ore('dustFluix') * 2)
    .outputs(item('appliedenergistics2:quartz_vibrant_glass') * 1)
    .duration(100)
    .property("temperature", 1800)
    .EUt(120)
    .buildAndRegister()

//奥术工作台破坏核心
mods.thaumcraft.arcane_workbench.shapedBuilder()
    .row('DAD')
    .row('BCB')
    .row('DAD')
    .key('A', ore('plateThaumium'))
    .key('B', ore('dustFluix'))
    .key('C', ore('circuitMv'))
    .key('D', ore('plateNetherQuartz'))
    .output(item('appliedenergistics2:material', 44) * 2)
    .aspect('aqua').aspect('perditio')
    .vis(25)
    .register()

//奥术工作台成型核心
mods.thaumcraft.arcane_workbench.shapedBuilder()
    .row('DAD')
    .row('BCB')
    .row('DAD')
    .key('A', ore('plateThaumium'))
    .key('B', ore('dustFluix'))
    .key('C', ore('circuitMv'))
    .key('D', ore('plateCertusQuartz'))
    .output(item('appliedenergistics2:material', 43) * 2)
    .aspect('terra').aspect('ordo')
    .vis(25)
    .register()

//注魔me输入总线
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .mainInput(item('appliedenergistics2:material', 44))
    .output(item('appliedenergistics2:part', 240))
    .aspect('aqua', 10)
    .aspect('perditio', 10)
    .input(ore('frameGtSteel'))
    .input(item('minecraft:sticky_piston'))
    .input(item('gregtech:meta_item_1', 158)) //mv传送带
    .input(item('gregtech:meta_item_1', 291)) //物品过滤覆盖板
    .instability(4)
    .register()

//注魔me输出总线
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .mainInput(item('appliedenergistics2:material', 43))
    .output(item('appliedenergistics2:part', 260))
    .aspect('terra', 10)
    .aspect('ordo', 10)
    .input(ore('frameGtSteel'))
    .input(item('minecraft:piston'))
    .input(item('gregtech:meta_item_1', 158)) //mv传送带
    .input(item('gregtech:meta_item_1', 291)) //物品过滤覆盖板
    .instability(4)
    .register()

//注魔me流体输入总线
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .mainInput(item('appliedenergistics2:material', 44))
    .output(item('appliedenergistics2:part', 241))
    .aspect('aqua', 20)
    .aspect('perditio', 20)
    .input(ore('frameGtSteel'))
    .input(ore('plateLapis'))
    .input(ore('plateLapis'))
    .input(ore('plate'))
    .input(item('minecraft:sticky_piston'))
    .input(item('gregtech:meta_item_1', 143)) //mv泵
    .input(item('gregtech:meta_item_1', 290)) //流体过滤覆盖板
    .instability(4)
    .register()

//注魔me流体输出总线
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .mainInput(item('appliedenergistics2:material', 43))
    .output(item('appliedenergistics2:part', 261))
    .aspect('terra', 20)
    .aspect('ordo', 20)
    .input(ore('frameGtSteel'))
    .input(ore('plateLapis'))
    .input(ore('plateLapis'))
    .input(item('minecraft:piston'))
    .input(item('gregtech:meta_item_1', 143)) //mv泵
    .input(item('gregtech:meta_item_1', 290)) //流体过滤覆盖板
    .instability(4)
    .register()

//注魔me能源接收器
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .mainInput(ore('crystalPureFluix'))
    .output(item('appliedenergistics2:energy_acceptor'))
    .aspect('potentia', 25)
    .aspect('praecantatio', 25)
    .aspect('ordo', 10)
    .aspect('fabrico', 10)
    .input(item('thaumcraft:morphic_resonator'))
    .input(item('thaumcraft:vis_resonator'))
    .input(ore('circuitLv'))
    .input(ore('plateThaumium'))
    .input(ore('plateThaumium'))
    .input(item('appliedenergistics2:quartz_glass'))
    .input(item('appliedenergistics2:quartz_glass'))
    .instability(6)
    .register()

//注魔me控制器
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .mainInput(item('appliedenergistics2:energy_acceptor'))
    .output(item('appliedenergistics2:controller'))
    .aspect('potentia', 50)
    .aspect('praecantatio', 25)
    .aspect('ordo', 10)
    .aspect('fabrico', 20)
    .input(item('thaumcraft:vis_battery'))
    .input(ore('circuitMv'))
    .input(ore('circuitMv'))
    .input(ore('plateThaumium'))
    .input(ore('plateThaumium'))
    .input(item('appliedenergistics2:quartz_vibrant_glass'))
    .input(item('appliedenergistics2:quartz_vibrant_glass'))
    .instability(6)
    .register()

//照明面板
mods.thaumcraft.arcane_workbench.shapedBuilder()
    .row('DAD')
    .row('BCB')
    .row('DAD')
    .key('A', ore('dustGlowstone'))
    .key('B', ore('plateThaumium'))
    .key('C', ore('dustRedstone'))
    .key('D', item('appliedenergistics2:quartz_glass'))
    .output(item('appliedenergistics2:part', 180) * 2)
    .aspect('ignis')
    .vis(10)
    .register()

//me终端
mods.thaumcraft.arcane_workbench.shapedBuilder()
    .row('AB ')
    .row('CD ')
    .row('   ')
    .key('A', item('appliedenergistics2:material', 43))
    .key('B', item('appliedenergistics2:part', 180))
    .key('C', ore('circuitLv'))
    .key('D', item('appliedenergistics2:material', 44))
    .output(item('appliedenergistics2:part', 380))
    .aspect('ordo')
    .vis(20)
    .register()

//me合成终端
mods.thaumcraft.arcane_workbench.shapedBuilder()
    .row('AB ')
    .row('C  ')
    .row('   ')
    .key('A', item('appliedenergistics2:part', 380))
    .key('B', ore('workbench'))
    .key('C', ore('circuitMv'))
    .output(item('appliedenergistics2:part', 360))
    .aspect('ordo')
    .vis(20)
    .register()

//me流体终端
mods.thaumcraft.arcane_workbench.shapedBuilder()
    .row('AB ')
    .row('C  ')
    .row('   ')
    .key('A', item('appliedenergistics2:part', 380))
    .key('B', ore('plateLapis'))
    .key('C', ore('circuitMv'))
    .output(item('appliedenergistics2:part', 520))
    .aspect('ordo')
    .vis(20)
    .register()

//me箱子
mods.thaumcraft.arcane_workbench.shapedBuilder()
    .row('DAD')
    .row('FCF')
    .row('EBE')
    .key('A', item('appliedenergistics2:part', 380))
    .key('B', ore('crystalPureFluix'))
    .key('C', ore('chest'))
    .key('D', item('appliedenergistics2:quartz_glass'))
    .key('E', ore('plateThaumium'))
    .key('F', ore('plateBrass'))
    .output(item('appliedenergistics2:chest'))
    .aspect('ordo', 2).aspect('terra', 2)
    .vis(25)
    .register()

//注魔me存储总线
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .mainInput(item('appliedenergistics2:chest'))
    .output(item('appliedenergistics2:part', 220))
    .aspect('motus', 10)
    .aspect('ordo', 10)
    .aspect('terra', 10)
    .aspect('aqua', 10)
    .aspect('perditio', 10)
    .input(item('thaumcraft:morphic_resonator'))
    .input(item('appliedenergistics2:part', 240))
    .input(item('appliedenergistics2:part', 260))
    .instability(4)
    .register()

//注魔me流体存储总线
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .mainInput(item('appliedenergistics2:chest'))
    .output(item('appliedenergistics2:part', 221))
    .aspect('motus', 10)
    .aspect('ordo', 10)
    .aspect('terra', 10)
    .aspect('aqua', 10)
    .aspect('perditio', 10)
    .input(item('thaumcraft:morphic_resonator'))
    .input(item('appliedenergistics2:part', 241))
    .input(item('appliedenergistics2:part', 261))
    .instability(4)
    .register()

//注魔me接口
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .mainInput(item('appliedenergistics2:chest'))
    .output(item('appliedenergistics2:interface') * 2)
    .aspect('motus', 10)
    .aspect('ordo', 10)
    .aspect('terra', 10)
    .aspect('aqua', 10)
    .aspect('perditio', 10)
    .input(ore('plateThaumium'))
    .input(ore('plateThaumium'))
    .input(ore('plateThaumium'))
    .input(ore('plateThaumium'))
    .input(item('appliedenergistics2:part', 240))
    .input(item('appliedenergistics2:part', 260))
    .input(item('appliedenergistics2:quartz_glass'))
    .input(item('appliedenergistics2:quartz_glass'))
    .instability(4)
    .register()

//注魔me流体接口
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .mainInput(item('appliedenergistics2:chest'))
    .output(item('appliedenergistics2:fluid_interface') * 2)
    .aspect('motus', 10)
    .aspect('ordo', 10)
    .aspect('terra', 10)
    .aspect('aqua', 10)
    .aspect('perditio', 10)
    .input(ore('plateLapis'))
    .input(ore('plateLapis'))
    .input(ore('plateLapis'))
    .input(ore('plateLapis'))
    .input(item('appliedenergistics2:part', 241))
    .input(item('appliedenergistics2:part', 261))
    .input(item('appliedenergistics2:quartz_vibrant_glass'))
    .input(item('appliedenergistics2:quartz_vibrant_glass'))
    .instability(4)
    .register()

//注魔me驱动器
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .mainInput(item('appliedenergistics2:chest'))
    .output(item('appliedenergistics2:drive'))
    .aspect('vacuos', 64)
    .aspect('aer', 20)
    .aspect('ignis', 20)
    .aspect('ordo', 20)
    .aspect('terra', 20)
    .aspect('aqua', 20)
    .aspect('perditio', 20)
    .input(ore('plateThaumium'))
    .input(ore('plateThaumium'))
    .input(ore('plateThaumium'))
    .input(ore('plateThaumium'))
    .input(ore('circuitHv'))
    .input(item('gregtech:machine', 1561)) //超级箱II
    .input(ore('frameGtPolytetrafluoroethylene'))
    .instability(6)
    .register()

//注魔分子装配室
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .mainInput(ore('workbench'))
    .output(item('appliedenergistics2:molecular_assembler'))
    .aspect('cognitio', 64)
    .aspect('humanus', 8)
    .aspect('fabrico', 32)
    .input(item('appliedenergistics2:quartz_vibrant_glass'))
    .input(item('appliedenergistics2:quartz_vibrant_glass'))
    .input(item('appliedenergistics2:quartz_vibrant_glass'))
    .input(item('appliedenergistics2:quartz_vibrant_glass'))
    .input(item('gregtech:machine', 111)) //mv组装机
    .input(ore('circuitHv'))
    .input(item('appliedenergistics2:material', 43))
    .input(item('appliedenergistics2:material', 44))
    .instability(8)
    .register()

//1k 4k 16k元件（删除了工作台配方）
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .mainInput(item('thaumcraft:vis_resonator'))
    .output(item('appliedenergistics2:material', 35))
    .aspect('vacuos', 8)
    .aspect('ordo', 8)
    .aspect('praecantatio', 8)
    .input(ore('frameGtSteel'))
    .input(ore('crystalCertusQuartz'))
    .input(ore('crystalCertusQuartz'))
    .input(ore('crystalCertusQuartz'))
    .input(ore('crystalCertusQuartz'))
    .input(ore('plateRedstone'))
    .input(ore('plateRedstone'))
    .input(ore('plateRedstone'))
    .input(ore('plateRedstone'))
    .input(ore('circuitLv'))
    .instability(2)
    .register()

mods.thaumcraft.infusion_crafting.recipeBuilder()
    .mainInput(item('thaumcraft:vis_resonator'))
    .output(item('appliedenergistics2:material', 36))
    .aspect('vacuos', 16)
    .aspect('ordo', 16)
    .aspect('praecantatio', 16)
    .input(ore('frameGtAluminium'))
    .input(ore('crystalCertusQuartz'))
    .input(ore('crystalCertusQuartz'))
    .input(ore('crystalCertusQuartz'))
    .input(ore('crystalCertusQuartz'))
    .input(ore('plateRedstone'))
    .input(ore('plateRedstone'))
    .input(ore('plateRedstone'))
    .input(ore('plateRedstone'))
    .input(ore('circuitMv'))
    .instability(4)
    .register()

mods.thaumcraft.infusion_crafting.recipeBuilder()
    .mainInput(item('thaumcraft:morphic_resonator'))
    .output(item('appliedenergistics2:material', 37))
    .aspect('vacuos', 32)
    .aspect('ordo', 32)
    .aspect('praecantatio', 32)
    .input(ore('frameGtStainlessSteel'))
    .input(ore('crystalCertusQuartz'))
    .input(ore('crystalCertusQuartz'))
    .input(ore('crystalCertusQuartz'))
    .input(ore('crystalCertusQuartz'))
    .input(ore('plateRedstone'))
    .input(ore('plateRedstone'))
    .input(ore('plateRedstone'))
    .input(ore('plateRedstone'))
    .input(ore('circuitHv'))
    .instability(6)
    .register()

//合成单元
mods.thaumcraft.arcane_workbench.shapedBuilder()
    .row('DAD')
    .row('BCB')
    .row('DAD')
    .key('A', item('appliedenergistics2:quartz_vibrant_glass'))
    .key('B', ore('circuitLv'))
    .key('C', ore('workbench'))
    .key('D', ore('plateThaumium'))
    .output(item('appliedenergistics2:crafting_unit'))
    .aspect('aer').aspect('ignis').aspect('aqua').aspect('terra').aspect('ordo').aspect('perditio')
    .vis(25)
    .register()

//能量单元
mods.thaumcraft.arcane_workbench.shapedBuilder()
    .row('DAD')
    .row('BCB')
    .row('DAD')
    .key('A', ore('crystalCertusQuartz'))
    .key('B', ore('circuitLv'))
    .key('C', item('thaumcraft:vis_battery'))
    .key('D', ore('plateThaumium'))
    .output(item('appliedenergistics2:energy_cell'))
    .aspect('ignis', 3).aspect('ordo',  3)
    .vis(50)
    .register()

//致密能量单元
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .mainInput(item('thaumcraft:vis_battery'))
    .output(item('appliedenergistics2:dense_energy_cell'))
    .aspect('potentia', 256)
    .input(item('appliedenergistics2:energy_cell'))
    .input(item('appliedenergistics2:energy_cell'))
    .input(item('appliedenergistics2:energy_cell'))
    .input(item('appliedenergistics2:energy_cell'))
    .input(item('appliedenergistics2:energy_cell'))
    .input(item('appliedenergistics2:energy_cell'))
    .input(item('appliedenergistics2:energy_cell'))
    .input(item('appliedenergistics2:energy_cell'))
    .instability(6)
    .register()

//me安全终端
mods.thaumcraft.arcane_workbench.shapedBuilder()
    .row('DAD')
    .row('BCB')
    .row('DAD')
    .key('A', item('appliedenergistics2:chest'))
    .key('B', ore('circuitHv'))
    .key('C', item('appliedenergistics2:material', 37))
    .key('D', ore('plateThaumium'))
    .output(item('appliedenergistics2:security_station'))
    .aspect('aer', 4).aspect('ignis', 4).aspect('aqua', 4).aspect('terra', 4).aspect('ordo', 4).aspect('perditio', 4)
    .vis(100)
    .register()

//fluix珍珠
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .mainInput(ore('enderpearl'))
    .output(item('appliedenergistics2:material', 9))
    .aspect('vacuos', 16)
    .aspect('potentia', 16)
    .input(ore('dustFluix'))
    .input(ore('dustFluix'))
    .input(ore('dustFluix'))
    .input(ore('dustFluix'))
    .input(ore('dustFluix'))
    .input(ore('dustFluix'))
    .input(ore('dustFluix'))
    .input(ore('dustFluix'))
    .instability(4)
    .register()

//无线接收器
mods.thaumcraft.infusion_crafting.recipeBuilder()
    .mainInput(item('appliedenergistics2:material', 9))
    .output(item('appliedenergistics2:material', 41))
    .aspect('vacuos', 16)
    .aspect('praecantatio', 16)
    .aspect('alienis', 32)
    .input(item('appliedenergistics2:part', 140))
    .input(item('appliedenergistics2:part', 140))
    .input(item('appliedenergistics2:part', 140))
    .input(item('appliedenergistics2:part', 140))
    .input(ore('plateThaumium'))
    .input(ore('plateThaumium'))
    .input(item('gregtech:meta_item_1', 218)) //mv传感器
    .instability(4)
    .register()

//无线终端
mods.thaumcraft.arcane_workbench.shapedBuilder()
    .row('DAD')
    .row('BCB')
    .row('DED')
    .key('A', ore('circuitHv'))
    .key('B', item('appliedenergistics2:material', 41))
    .key('C', item('appliedenergistics2:part', 380))
    .key('D', ore('plateThaumium'))
    .key('E', item('appliedenergistics2:dense_energy_cell'))
    .output(item('appliedenergistics2:wireless_terminal'))
    .aspect('aer', 6).aspect('ignis', 6).aspect('aqua', 6).aspect('terra', 6).aspect('ordo', 6).aspect('perditio', 6)
    .vis(150)
    .register()
