//石头处理 0 1 2 3 5 6 8 
//辉长岩
mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth'))
    .outputs(metaitem('dustGabbro'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()

mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_cobble'))
    .outputs(metaitem('dustGabbro'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()
	
mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_bricks'))
    .outputs(metaitem('dustGabbro'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()
	
mods.gregtech.forge_hammer.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth'))
    .outputs(item('gtqtcore:gtqt_stone_cobble'))
	.EUt(4)
    .duration(12) 
    .buildAndRegister()
	
mods.gregtech.extruder.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth'))
    .outputs(item('gtqtcore:gtqt_stone_bricks'))
	.EUt(8)
    .duration(240) 
	.notConsumable(item('gregtech:meta_item_1', 36))
    .buildAndRegister()
	
mods.gregtech.extruder.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_cobble'))
    .outputs(item('gtqtcore:gtqt_stone_smooth'))
	.EUt(8)
    .duration(240) 
	.notConsumable(item('gregtech:meta_item_1', 43))
    .buildAndRegister()
	
//1
mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',1))
    .outputs(metaitem('dustGneiss'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()

mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_cobble',1))
    .outputs(metaitem('dustGneiss'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()
	
mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_bricks',1))
    .outputs(metaitem('dustGneiss'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()
	
mods.gregtech.forge_hammer.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',1))
    .outputs(item('gtqtcore:gtqt_stone_cobble',1))
	.EUt(4)
    .duration(12) 
    .buildAndRegister()
	
mods.gregtech.extruder.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',1))
    .outputs(item('gtqtcore:gtqt_stone_bricks',1))
	.EUt(8)
    .duration(240) 
	.notConsumable(item('gregtech:meta_item_1', 36))
    .buildAndRegister()
	
mods.gregtech.extruder.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_cobble',1))
    .outputs(item('gtqtcore:gtqt_stone_smooth',1))
	.EUt(8)
    .duration(240) 
	.notConsumable(item('gregtech:meta_item_1', 43))
    .buildAndRegister()
	
//2
mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',2))
    .outputs(metaitem('dustLimestone'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()

mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_cobble',2))
    .outputs(metaitem('dustLimestone'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()
	
mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_bricks',2))
    .outputs(metaitem('dustLimestone'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()
	
mods.gregtech.forge_hammer.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',2))
    .outputs(item('gtqtcore:gtqt_stone_cobble',2))
	.EUt(4)
    .duration(12) 
    .buildAndRegister()
	
mods.gregtech.extruder.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',2))
    .outputs(item('gtqtcore:gtqt_stone_bricks',2))
	.EUt(8)
    .duration(240) 
	.notConsumable(item('gregtech:meta_item_1', 36))
    .buildAndRegister()
	
mods.gregtech.extruder.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_cobble',2))
    .outputs(item('gtqtcore:gtqt_stone_smooth',2))
	.EUt(8)
    .duration(240) 
	.notConsumable(item('gregtech:meta_item_1', 43))
    .buildAndRegister()
	
//3
mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',3))
	.outputs(metaitem('dustPhyllite'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()

mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_cobble',3))
	.outputs(metaitem('dustPhyllite'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()
	
mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_bricks',3))
    .outputs(metaitem('dustPhyllite'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()
	
mods.gregtech.forge_hammer.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',3))
    .outputs(item('gtqtcore:gtqt_stone_cobble',3))
	.EUt(4)
    .duration(12) 
    .buildAndRegister()
	
mods.gregtech.extruder.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',3))
    .outputs(item('gtqtcore:gtqt_stone_bricks',3))
	.EUt(8)
    .duration(240) 
	.notConsumable(item('gregtech:meta_item_1', 36))
    .buildAndRegister()
	
mods.gregtech.extruder.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_cobble',3))
    .outputs(item('gtqtcore:gtqt_stone_smooth',3))
	.EUt(8)
    .duration(240) 
	.notConsumable(item('gregtech:meta_item_1', 43))
    .buildAndRegister()
	
//5
mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',5))
	.outputs(metaitem('dustShale'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()

mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_cobble',5))
	.outputs(metaitem('dustShale'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()
	
mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_bricks',5))
    .outputs(metaitem('dustShale'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()
	
mods.gregtech.forge_hammer.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',5))
    .outputs(item('gtqtcore:gtqt_stone_cobble',5))
	.EUt(4)
    .duration(12) 
    .buildAndRegister()
	
mods.gregtech.extruder.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',5))
    .outputs(item('gtqtcore:gtqt_stone_bricks',5))
	.EUt(8)
    .duration(240) 
	.notConsumable(item('gregtech:meta_item_1', 36))
    .buildAndRegister()
	
mods.gregtech.extruder.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_cobble',5))
    .outputs(item('gtqtcore:gtqt_stone_smooth',5))
	.EUt(8)
    .duration(240) 
	.notConsumable(item('gregtech:meta_item_1', 43))
    .buildAndRegister()

//6
mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',6))
	.outputs(metaitem('dustSlate'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()

mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_cobble',6))
	.outputs(metaitem('dustSlate'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()
	
mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_bricks',6))
    .outputs(metaitem('dustSlate'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()
	
mods.gregtech.forge_hammer.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',6))
    .outputs(item('gtqtcore:gtqt_stone_cobble',6))
	.EUt(4)
    .duration(12) 
    .buildAndRegister()
	
mods.gregtech.extruder.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',6))
    .outputs(item('gtqtcore:gtqt_stone_bricks',6))
	.EUt(8)
    .duration(240) 
	.notConsumable(item('gregtech:meta_item_1', 36))
    .buildAndRegister()
	
mods.gregtech.extruder.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_cobble',6))
    .outputs(item('gtqtcore:gtqt_stone_smooth',6))
	.EUt(8)
    .duration(240) 
	.notConsumable(item('gregtech:meta_item_1', 43))
    .buildAndRegister()
	
//8
mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',8))
	.outputs(metaitem('dustKimberlite'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()

mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_cobble',8))
	.outputs(metaitem('dustKimberlite'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()
	
mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_bricks',8))
    .outputs(metaitem('dustKimberlite'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()
	
mods.gregtech.forge_hammer.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',8))
    .outputs(item('gtqtcore:gtqt_stone_cobble',8))
	.EUt(4)
    .duration(12) 
    .buildAndRegister()
	
mods.gregtech.extruder.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',8))
    .outputs(item('gtqtcore:gtqt_stone_bricks',8))
	.EUt(8)
    .duration(240) 
	.notConsumable(item('gregtech:meta_item_1', 36))
    .buildAndRegister()
	
mods.gregtech.extruder.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_cobble',8))
    .outputs(item('gtqtcore:gtqt_stone_smooth',8))
	.EUt(8)
    .duration(240) 
	.notConsumable(item('gregtech:meta_item_1', 43))
    .buildAndRegister()
	
//4
mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',4))
	.outputs(metaitem('dustQuartzite'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()

mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_cobble',4))
	.outputs(metaitem('dustQuartzite'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()
	
mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_bricks',4))
    .outputs(metaitem('dustQuartzite'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()
	
mods.gregtech.forge_hammer.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',4))
    .outputs(item('gtqtcore:gtqt_stone_cobble',4))
	.EUt(4)
    .duration(12) 
    .buildAndRegister()
	
mods.gregtech.extruder.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',4))
    .outputs(item('gtqtcore:gtqt_stone_bricks',4))
	.EUt(8)
    .duration(240) 
	.notConsumable(item('gregtech:meta_item_1', 36))
    .buildAndRegister()
	
mods.gregtech.extruder.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_cobble',4))
    .outputs(item('gtqtcore:gtqt_stone_smooth',4))
	.EUt(8)
    .duration(240) 
	.notConsumable(item('gregtech:meta_item_1', 43))
    .buildAndRegister()
	
//7
mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',7))
	.outputs(metaitem('dustSoapstone'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()

mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_cobble',7))
	.outputs(metaitem('dustSoapstone'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()
	
mods.gregtech.macerator.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_bricks',7))
    .outputs(metaitem('dustSoapstone'))
	.EUt(2)
    .duration(150) 
    .buildAndRegister()
	
mods.gregtech.forge_hammer.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',7))
    .outputs(item('gtqtcore:gtqt_stone_cobble',7))
	.EUt(4)
    .duration(12) 
    .buildAndRegister()
	
mods.gregtech.extruder.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_smooth',7))
    .outputs(item('gtqtcore:gtqt_stone_bricks',7))
	.EUt(8)
    .duration(240) 
	.notConsumable(item('gregtech:meta_item_1', 36))
    .buildAndRegister()
	
mods.gregtech.extruder.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_stone_cobble',7))
    .outputs(item('gtqtcore:gtqt_stone_smooth',7))
	.EUt(8)
    .duration(240) 
	.notConsumable(item('gregtech:meta_item_1', 43))
    .buildAndRegister()