mods.gregtech.centrifuge.recipeBuilder()
	.fluidInputs(fluid('tar')*2000)
    .fluidOutputs(fluid('pure_tar')*1000)
    .duration(200) 
    .EUt(120) 
    .buildAndRegister()
	
// 铈粉 * 1
mods.gregtech.electrolyzer.removeByInput(30, [metaitem('dustCeriumOxide') * 3], null)
// 稀土 * 1
mods.gregtech.electrolyzer.removeByInput(30, [metaitem('dustMonazite') * 2], null)
// 气态氧 * 2000
mods.gregtech.electrolyzer.removeByInput(30, [metaitem('dustYanghuaha') * 3], null)
mods.gregtech.centrifuge.removeByInput(20, [metaitem('dustRareEarth')], null)

mods.gregtech.chemical_bath.recipeBuilder()
    .inputs(ore('crushedNickel'))
	.outputs(item('gregtech:meta_crushed_purified', 69))
	.fluidInputs(fluid('mercury')*100)
    .duration(200) 
	.EUt(30)
    .buildAndRegister()
	
mods.gregtech.extractor.recipeBuilder()
    .inputs(item('biomesoplenty:honey_block'))
    .outputs(item('minecraft:slime_ball')*4)
	.EUt(30)
    .duration(200) 
    .buildAndRegister()
// 史莱姆->胶水
mods.gregtech.extractor.recipeBuilder()
    .inputs(ore('blockSlime'))
    .fluidOutputs(fluid('glue')*100)
	.EUt(30)
    .duration(200) 
    .buildAndRegister()

mods.gregtech.extractor.recipeBuilder()
    .inputs(ore('blockSlimeCongealed'))
    .fluidOutputs(fluid('glue')*500)
	.EUt(30)
    .duration(200) 
    .buildAndRegister()

mods.gregtech.extractor.recipeBuilder()
    .inputs(ore('slimeball'))
    .fluidOutputs(fluid('glue')*10)
	.EUt(30)
    .duration(200) 
    .buildAndRegister()
	
//交错 橡胶
mods.gregtech.extractor.recipeBuilder()
    .inputs(item('thebetweenlands:items_misc', 23))
    .fluidOutputs(fluid('rubber')*144)
	.EUt(30)
    .duration(200) 
    .buildAndRegister()
	
mods.gregtech.extractor.recipeBuilder()
    .inputs(item('thebetweenlands:log_rubber'))
    .fluidOutputs(fluid('rubber')*144)
	.EUt(30)
    .duration(200) 
    .buildAndRegister()
	
mods.gregtech.fermenter.recipeBuilder()
    .inputs(ore('listAllseed'))
	.fluidInputs(fluid('water')*100)
    .fluidOutputs(fluid('biomass')*100)
	.EUt(30)
    .duration(10) 
    .buildAndRegister()
	
mods.gregtech.fermenter.recipeBuilder()
    .inputs(ore('listAllfruit'))
	.fluidInputs(fluid('water')*100)
    .fluidOutputs(fluid('biomass')*100)
	.EUt(30)
    .duration(10) 
    .buildAndRegister()
	
mods.gregtech.fermenter.recipeBuilder()
    .inputs(ore('listAllveggie'))
	.fluidInputs(fluid('water')*100)
    .fluidOutputs(fluid('biomass')*100)
	.EUt(30)
    .duration(10) 
    .buildAndRegister()
	
mods.gregtech.fermenter.recipeBuilder()
    .inputs(ore('listAllgreenveggie'))
	.fluidInputs(fluid('water')*100)
    .fluidOutputs(fluid('biomass')*100)
	.EUt(30)
    .duration(10) 
    .buildAndRegister()
	
mods.gregtech.fermenter.recipeBuilder()
    .inputs(ore('listAllgrain'))
	.fluidInputs(fluid('water')*100)
    .fluidOutputs(fluid('biomass')*100)
	.EUt(30)
    .duration(10) 
    .buildAndRegister()
	
mods.gregtech.fermenter.recipeBuilder()
    .inputs(ore('treeSapling'))
	.fluidInputs(fluid('water')*100)
    .fluidOutputs(fluid('biomass')*100)
	.EUt(30)
    .duration(10) 
    .buildAndRegister()
	
mods.gregtech.macerator.recipeBuilder()
    .inputs(item('biomesoplenty:fleshchunk'))
	.outputs(item('gregtech:meta_dust', 1616))
	.EUt(30)
    .duration(10) 
    .buildAndRegister()