mods.gregtech.centrifuge.recipeBuilder()
	.fluidInputs(fluid('tar')*2000)
    .fluidOutputs(fluid('pure_tar')*1000)
    .duration(200) 
    .EUt(120) 
    .buildAndRegister()
	
// 气态氧 * 2000
mods.gregtech.centrifuge.removeByInput(20, [metaitem('dustRareEarth')], null)

mods.gregtech.extractor.recipeBuilder()
    .inputs(item('biomesoplenty:honey_block'))
    .outputs(item('minecraft:slime_ball')*4)
	.EUt(30)
    .duration(200) 
    .buildAndRegister()
	
// 史莱姆->胶水
mods.gregtech.extractor.recipeBuilder()
    .inputs(ore('blockSlime'))
    .fluidOutputs(fluid('glue')*100)
	.EUt(30)
    .duration(200) 
    .buildAndRegister()

mods.gregtech.extractor.recipeBuilder()
    .inputs(ore('blockSlimeCongealed'))
    .fluidOutputs(fluid('glue')*500)
	.EUt(30)
    .duration(200) 
    .buildAndRegister()

mods.gregtech.extractor.recipeBuilder()
    .inputs(ore('slimeball'))
    .fluidOutputs(fluid('glue')*10)
	.EUt(30)
    .duration(200) 
    .buildAndRegister()
	
//交错 橡胶
mods.gregtech.extractor.recipeBuilder()
    .inputs(item('thebetweenlands:items_misc', 23))
    .fluidOutputs(fluid('latex')*144)
	.EUt(30)
    .duration(200) 
    .buildAndRegister()
	
mods.gregtech.extractor.recipeBuilder()
    .inputs(item('thebetweenlands:log_rubber'))
    .fluidOutputs(fluid('latex')*144)
	.EUt(30)
    .duration(200) 
    .buildAndRegister()
	
mods.gregtech.macerator.recipeBuilder()
    .inputs(item('biomesoplenty:fleshchunk'))
	.outputs(item('gregtech:meta_dust', 1616))
	.EUt(30)
    .duration(10) 
    .buildAndRegister()