//Lazy AE的魔改
//ban
crafting.removeByOutput(item('threng:machine'))
crafting.removeByOutput(item('threng:machine',1))
crafting.removeByOutput(item('threng:machine',2))
crafting.removeByOutput(item('threng:machine',5))

//含碳复合物
crafting.removeByOutput(item('threng:material', 1))
mods.gregtech.mixer.recipeBuilder()
        .inputs(ore('dustFluix')*2)
        .inputs(ore('dustSiliconNanoparticles')*2)
        .inputs(ore('dustGraphite'))
        .inputs(ore('dustUranium'))
        .outputs(item('threng:material', 1)*6)
        .EUt(1960)
        .duration(800)
        .buildAndRegister()

//flux钢锭
furnace.removeByInput(item('threng:material', 2))
mods.gregtech.electric_blast_furnace.recipeBuilder()
        .inputs(item('threng:material', 2))
        .outputs(item('threng:material'))
        .fluidInputs(fluid('argon')*2000)
        .EUt(7280)
        .property("temperature", 6000)
        .duration(1200)
        .buildAndRegister()

//镀层铁锭
mods.gregtech.chemical_reactor.recipeBuilder()
        .inputs(ore('ingotIncoloyDs'))
        .inputs(item('threng:material', 1))
        .outputs(item('threng:material', 2))
        .fluidInputs(fluid('mutagen')*400)
        .duration(200)
        .EUt(7280)
        .buildAndRegister()

//逻辑单元
crafting.removeByOutput(item('threng:material', 4))
mods.gregtech.circuit_assembler.recipeBuilder()
        .inputs(item('gregtech:meta_item_1', 406)*4)
        .inputs(item('gtqtcore:gtqt_meta_item_1', 440))
        .inputs(item('threng:material')*4)
        .inputs(item('gregtech:meta_item_1', 605)*8)
        .inputs(item('gregtech:meta_item_1', 530)*4)
        .inputs(item('gregtech:meta_item_1', 532)*4)
        .fluidInputs(fluid('peek')*1440)
        .outputs(item('threng:material', 4))
        .duration(200)
        .EUt(7280)
        .buildAndRegister()


//并行处理器
mods.gregtech.circuit_assembler.recipeBuilder()
        .inputs(ore('plateMagnetoResonatic'))
        .inputs(item('gtqtcore:gtqt_meta_item_1', 440))
        .inputs(item('threng:material')*4)
        .inputs(item('gregtech:meta_item_1', 600)*8)
        .inputs(item('gregtech:meta_item_1', 530)*4)
        .inputs(item('gregtech:meta_item_1', 532)*4)
        .fluidInputs(fluid('peek')*1440)
        .outputs(item('threng:material', 6))
        .duration(200)
        .EUt(7280)
        .buildAndRegister()

//推测核心
mods.gregtech.circuit_assembler.recipeBuilder()
        .inputs(item('threng:material', 13))
        .inputs(item('gtqtcore:gtqt_meta_item_1', 440))
        .inputs(item('threng:material')*4)
        .inputs(item('gregtech:meta_item_1', 601)*8)
        .inputs(item('gregtech:meta_item_1', 530)*4)
        .inputs(item('gregtech:meta_item_1', 532)*4)
        .fluidInputs(fluid('peek')*1440)
        .outputs(item('threng:material', 14))
        .duration(200)
        .EUt(7280)
        .buildAndRegister()

//框架
crafting.removeByOutput(item('threng:big_assembler'))
mods.gregtech.assembler.recipeBuilder()
        .inputs(item('gregtech:machine', 990))
        .inputs(item('gtqtcore:gtqt_meta_item_1', 440)*2)
        .inputs(item('threng:material')*16)
        .inputs(ore('frameGtCarbonNanotube')*8)
        .inputs(ore('plateStaballoy')*4)
        .inputs(ore('gearSmallPpb')*8)
        .fluidInputs(fluid('peek')*1440)
        .outputs(item('threng:big_assembler')*2)
        .duration(200)
        .EUt(7280)
        .buildAndRegister()

//外壁
crafting.removeByOutput(item('threng:big_assembler', 1))
mods.gregtech.assembler.recipeBuilder()
        .inputs(item('threng:big_assembler'))
        .inputs(ore('plateNaquadah')*2)
        .inputs(ore('ringRhodiumPlatedPalladium')*4)
        .fluidInputs(fluid('peek')*1440)
        .outputs(item('threng:big_assembler',1))
        .duration(200)
        .EUt(7280)
        .buildAndRegister()