//me接口 1刻金框架+两核心+6钛板=16个
//me流体接口 1秘银框架+两核心+6钛板=16个
mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(ore('plateTitanium') * 6)
    .inputs(ore('frameGtKeqinggold'))
    .inputs(item('appliedenergistics2:material', 43))
    .inputs(item('appliedenergistics2:material', 44))
    .fluidInputs(fluid('magic') * 100)
    .outputs(item('appliedenergistics2:interface') * 16)
    .duration(160)
	.circuitMeta(20)
    .EUt(1920)
    .buildAndRegister()

mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(ore('plateTitanium') * 6)
    .inputs(ore('frameGtHyperdimensionalSilver'))
    .inputs(item('appliedenergistics2:material', 43))
    .inputs(item('appliedenergistics2:material', 44))
    .fluidInputs(fluid('magic') * 100)
    .outputs(item('appliedenergistics2:fluid_interface') * 16)
    .duration(160)
	.circuitMeta(20)
    .EUt(1920)
    .buildAndRegister()

//核心
mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(ore('plateCertusQuartz') * 6)
    .inputs(ore('dustFluix'))
    .fluidInputs(fluid('magic') * 100)
    .outputs(item('appliedenergistics2:material', 44) * 16)
    .duration(160)
	.circuitMeta(1)
    .EUt(480)
    .buildAndRegister()

mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(ore('plateNetherQuartz') * 6)
    .inputs(ore('dustFluix'))
    .fluidInputs(fluid('magic') * 100)
    .outputs(item('appliedenergistics2:material', 43) * 16)
    .duration(160)
	.circuitMeta(1)
    .EUt(480)
    .buildAndRegister()

//三种电路板
mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('appliedenergistics2:material', 16))
    .inputs(ore('plateRedAlloy'))
    .fluidInputs(fluid('mansussteel') * 144)
    .outputs(item('appliedenergistics2:material', 23) * 16)
    .duration(160)
    .EUt(480)
    .buildAndRegister()

mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('appliedenergistics2:material', 17))
    .inputs(ore('plateRedAlloy'))
    .fluidInputs(fluid('mansussteel') * 144)
    .outputs(item('appliedenergistics2:material', 24) * 16)
    .duration(160)
    .EUt(480)
    .buildAndRegister()

mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('appliedenergistics2:material', 18))
    .inputs(ore('plateRedAlloy'))
    .fluidInputs(fluid('mansussteel') * 144)
    .outputs(item('appliedenergistics2:material', 22) * 16)
    .duration(160)
    .EUt(480)
    .buildAndRegister()    

//分子装配室 1刻金框架+4玻璃+2核心各2=4
mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('appliedenergistics2:quartz_vibrant_glass') * 4)
    .inputs(ore('frameGtKeqinggold'))
    .inputs(item('appliedenergistics2:material', 43) * 2)
    .inputs(item('appliedenergistics2:material', 44) * 2)
    .fluidInputs(fluid('magic') * 100)
    .outputs(item('appliedenergistics2:molecular_assembler') * 4)
    .circuitMeta(21)
    .duration(400)
    .EUt(7680)
    .buildAndRegister()

//p2p
mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(ore('crystalPureFluix') * 2)
    .inputs(ore('frameGtHyperdimensionalSilver'))
    .inputs(item('appliedenergistics2:material', 24))
    .fluidInputs(fluid('magic') * 100)
    .outputs(item('appliedenergistics2:part', 460) * 16)
    .circuitMeta(21)
    .duration(100)
    .EUt(1920)
    .buildAndRegister()

//玻璃线缆
mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('appliedenergistics2:part', 140) * 16)
    .inputs(ore('gemFluix'))
    .fluidInputs(fluid('mansussteel') * 144)
    .outputs(item('appliedenergistics2:part', 16) * 64)
    .duration(100)
    .EUt(480)
    .buildAndRegister()

//me驱动器
mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(ore('plateTitanium') * 4)
    .inputs(ore('frameGtKeqinggold'))
    .inputs(item('appliedenergistics2:part', 16) * 2)
    .inputs(item('appliedenergistics2:material', 24) * 2)
    .inputs(item('appliedenergistics2:material', 22) * 2)
    .fluidInputs(fluid('mansussteel') * 144)
    .outputs(item('appliedenergistics2:drive') * 8)
    .duration(400)
	.circuitMeta(20)
    .EUt(1920)
    .buildAndRegister()   

//me控制器
mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(ore('plateTungstenSteel') * 4)
    .inputs(ore('frameGtHyperdimensionalSilver'))
    .inputs(ore('crystalPureFluix') * 2)
    .inputs(item('appliedenergistics2:material', 23) * 4)
    .fluidInputs(fluid('mansussteel') * 144)
    .outputs(item('appliedenergistics2:controller') * 8)
    .duration(400)
	.circuitMeta(20)
    .EUt(1920)
    .buildAndRegister()   

//存储组件
mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('gregtech:meta_item_1', 591))
    .inputs(ore('circuitLv'))
    .inputs(item('appliedenergistics2:material', 22))
    .fluidInputs(fluid('magic') * 100)
    .outputs(item('appliedenergistics2:material', 35) * 4)
    .duration(320)
	.circuitMeta(22)
    .EUt(30)
    .buildAndRegister()

mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('gregtech:meta_item_1', 592))
    .inputs(ore('circuitMv'))
    .inputs(item('appliedenergistics2:material', 22))
    .fluidInputs(fluid('magic') * 200)
    .outputs(item('appliedenergistics2:material', 36) * 4)
    .duration(320)
	.circuitMeta(22)
    .EUt(120)
    .buildAndRegister()

mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('gregtech:meta_item_1', 602))
    .inputs(ore('circuitHv'))
    .inputs(item('appliedenergistics2:material', 22) * 4)
    .fluidInputs(fluid('magic') * 400)
    .outputs(item('appliedenergistics2:material', 37) * 4)
    .duration(320)
	.circuitMeta(22)
    .EUt(480)
    .buildAndRegister()

mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('gregtech:meta_item_1', 603))
    .inputs(ore('circuitEv'))
    .inputs(item('appliedenergistics2:material', 22) * 4)
    .fluidInputs(fluid('magic') * 800)
    .outputs(item('appliedenergistics2:material', 38) * 4)
    .duration(320)
	.circuitMeta(22)
    .EUt(1920)
    .buildAndRegister()

//256k+组件
mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('gregtech:meta_item_1', 604))
    .inputs(ore('circuitIv'))
    .inputs(item('appliedenergistics2:material', 22) * 16)
    .fluidInputs(fluid('magic') * 1600)
    .outputs(item('nae2:material', 19) * 4)
    .duration(320)
	.circuitMeta(22)
    .EUt(7680)
    .buildAndRegister()

mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('gregtech:meta_item_1', 605))
    .inputs(ore('circuitLuv'))
    .inputs(item('appliedenergistics2:material', 22) * 16)
    .fluidInputs(fluid('magic') * 3200)
    .outputs(item('nae2:material', 20) * 4)
    .duration(320)
	.circuitMeta(22)
    .EUt(30720)
    .buildAndRegister()

mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('gregtech:meta_item_1', 606))
    .inputs(ore('circuitZpm'))
    .inputs(item('appliedenergistics2:material', 22) * 64)
    .fluidInputs(fluid('magic') * 6400)
    .outputs(item('nae2:material', 21) * 4)
    .duration(320)
	.circuitMeta(22)
    .EUt(122880)
    .buildAndRegister()

mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_meta_item_1', 860))
    .inputs(ore('circuitUv'))
    .inputs(item('appliedenergistics2:material', 22) * 64)
    .fluidInputs(fluid('magic') * 12800)
    .outputs(item('nae2:material', 22) * 4)
    .duration(320)
	.circuitMeta(22)
    .EUt(491520)
    .buildAndRegister()

//流体
mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('gregtech:meta_item_1', 591))
    .inputs(ore('circuitLv'))
    .inputs(item('appliedenergistics2:material', 23))
    .fluidInputs(fluid('magic') * 100)
    .outputs(item('appliedenergistics2:material', 54) * 4)
    .duration(320)
	.circuitMeta(23)
    .EUt(30)
    .buildAndRegister()

mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('gregtech:meta_item_1', 592))
    .inputs(ore('circuitMv'))
    .inputs(item('appliedenergistics2:material', 23))
    .fluidInputs(fluid('magic') * 200)
    .outputs(item('appliedenergistics2:material', 55) * 4)
    .duration(320)
	.circuitMeta(23)
    .EUt(120)
    .buildAndRegister()

mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('gregtech:meta_item_1', 602))
    .inputs(ore('circuitHv'))
    .inputs(item('appliedenergistics2:material', 23) * 4)
    .fluidInputs(fluid('magic') * 400)
    .outputs(item('appliedenergistics2:material', 56) * 4)
    .duration(320)
	.circuitMeta(23)
    .EUt(480)
    .buildAndRegister()

mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('gregtech:meta_item_1', 603))
    .inputs(ore('circuitEv'))
    .inputs(item('appliedenergistics2:material', 23) * 4)
    .fluidInputs(fluid('magic') * 800)
    .outputs(item('appliedenergistics2:material', 57) * 4)
    .duration(320)
	.circuitMeta(23)
    .EUt(1920)
    .buildAndRegister()

//256k+流体组件
mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('gregtech:meta_item_1', 604))
    .inputs(ore('circuitIv'))
    .inputs(item('appliedenergistics2:material', 23) * 16)
    .fluidInputs(fluid('magic') * 1600)
    .outputs(item('nae2:material', 19) * 4)
    .duration(320)
	.circuitMeta(23)
    .EUt(7680)
    .buildAndRegister()

mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('gregtech:meta_item_1', 605))
    .inputs(ore('circuitLuv'))
    .inputs(item('appliedenergistics2:material', 23) * 16)
    .fluidInputs(fluid('magic') * 3200)
    .outputs(item('nae2:material', 20) * 4)
    .duration(320)
	.circuitMeta(23)
    .EUt(30720)
    .buildAndRegister()

mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('gregtech:meta_item_1', 606))
    .inputs(ore('circuitZpm'))
    .inputs(item('appliedenergistics2:material', 23) * 64)
    .fluidInputs(fluid('magic') * 6400)
    .outputs(item('nae2:material', 21) * 4)
    .duration(320)
	.circuitMeta(23)
    .EUt(122880)
    .buildAndRegister()

mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('gtqtcore:gtqt_meta_item_1', 860))
    .inputs(ore('circuitUv'))
    .inputs(item('appliedenergistics2:material', 23) * 64)
    .fluidInputs(fluid('magic') * 12800)
    .outputs(item('nae2:material', 22) * 4)
    .duration(320)
	.circuitMeta(23)
    .EUt(491520)
    .buildAndRegister()

//输入输出总线 4种
mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(ore('plateTitanium') * 4)
    .inputs(ore('frameGtKeqinggold'))
    .inputs(item('appliedenergistics2:interface'))
    .inputs(item('appliedenergistics2:material', 44))
    .fluidInputs(fluid('magic') * 100)
    .outputs(item('appliedenergistics2:part', 240) * 8)
    .duration(160)
	.circuitMeta(18)
    .EUt(480)
    .buildAndRegister()

mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(ore('plateTitanium') * 4)
    .inputs(ore('frameGtHyperdimensionalSilver'))
    .inputs(item('appliedenergistics2:interface'))
    .inputs(item('appliedenergistics2:material', 43))
    .fluidInputs(fluid('magic') * 100)
    .outputs(item('appliedenergistics2:part', 260) * 8)
    .duration(160)
	.circuitMeta(19)
    .EUt(480)
    .buildAndRegister()

mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(ore('plateTitanium') * 4)
    .inputs(ore('frameGtKeqinggold'))
    .inputs(item('appliedenergistics2:fluid_interface'))
    .inputs(item('appliedenergistics2:material', 44))
    .fluidInputs(fluid('magic') * 100)
    .outputs(item('appliedenergistics2:part', 241) * 8)
    .duration(160)
	.circuitMeta(18)
    .EUt(480)
    .buildAndRegister()

mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(ore('plateTitanium') * 4)
    .inputs(ore('frameGtHyperdimensionalSilver'))
    .inputs(item('appliedenergistics2:fluid_interface'))
    .inputs(item('appliedenergistics2:material', 43))
    .fluidInputs(fluid('magic') * 100)
    .outputs(item('appliedenergistics2:part', 261) * 8)
    .duration(160)
	.circuitMeta(19)
    .EUt(480)
    .buildAndRegister()

//无线重写
crafting.removeByOutput(item('appliedenergistics2:material', 9))
crafting.removeByOutput(item('appliedenergistics2:material', 41))
crafting.removeByOutput(item('ae2stuff:wireless'))

mods.gregtech.electric_blast_furnace.recipeBuilder()
    .inputs(ore('enderpearl'))
    .inputs(ore('dustFluix') * 4)
    .outputs(item('appliedenergistics2:material', 9))
    .duration(300)
    .property("temperature", 3600)
    .EUt(1920)
    .buildAndRegister()

mods.gregtech.assembler.recipeBuilder()
    .inputs(item('appliedenergistics2:material', 9))
	.inputs(item('gtqtcore:gtqt_meta_item_1', 88))
    .inputs(ore('plateTungstenSteel') * 3)
    .inputs(item('appliedenergistics2:part', 460))
    .outputs(item('appliedenergistics2:material', 41))
	.fluidInputs(fluid('zylon') * 100)
    .duration(160)
    .EUt(7680)
    .buildAndRegister()

mods.gregtech.assembler.recipeBuilder()
    .inputs(item('appliedenergistics2:material', 41))
    .inputs(ore('crystalPureFluix') * 4)
    .inputs(ore('frameGtTungstenSteel'))
    .inputs(item('gregtech:meta_item_1', 220))
    .outputs(item('ae2stuff:wireless') * 2)
    .duration(320)
    .EUt(1920)
    .buildAndRegister()

mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('appliedenergistics2:material', 9))
    .inputs(ore('plateMansussteel') * 3)
    .inputs(item('appliedenergistics2:part', 460))
    .outputs(item('appliedenergistics2:material', 41) * 4)
    .duration(160)
    .EUt(1920)
    .buildAndRegister()

mods.gregtech.magic_assembler.recipeBuilder()
    .inputs(item('appliedenergistics2:material', 41))
    .inputs(ore('crystalPureFluix') * 4)
    .inputs(ore('frameGtHyperdimensionalSilver'))
    .inputs(item('gregtech:meta_item_1', 220))
    .fluidInputs(fluid('magic') * 100)
    .outputs(item('ae2stuff:wireless') * 16)
    .duration(320)
    .EUt(1920)
    .buildAndRegister()