import crafttweaker.oredict.IOreDictEntry;
import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;
import crafttweaker.liquid.ILiquidStack;
mods.jei.JEI.removeAndHide(<galacticraftcore:basic_item:5>);
mods.jei.JEI.removeAndHide(<galacticraftcore:basic_item:4>);
mods.jei.JEI.removeAndHide(<galacticraftcore:basic_item:3>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_endergy_nugget:*>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_endergy_ingot:*>);
mods.jei.JEI.removeAndHide(<enderio:block_alloy_endergy:*>);
mods.jei.JEI.removeAndHide(<enderio:item_material:5>);
mods.jei.JEI.removeAndHide(<appliedenergistics2:material:5>);
mods.jei.JEI.removeAndHide(<forestry:ingot_bronze>);
mods.jei.JEI.removeAndHide(<appliedenergistics2:material:49>);
mods.jei.JEI.removeAndHide(<forestry:ingot_tin>);
mods.jei.JEI.removeAndHide(<forestry:ingot_copper>);
mods.jei.JEI.removeAndHide(<harvestcraft:saltitem>);
mods.jei.JEI.removeAndHide(<thaumcraft:plate:0>);
mods.jei.JEI.removeAndHide(<thaumcraft:plate:1>);
mods.jei.JEI.removeAndHide(<thaumcraft:metal_brass>);
mods.jei.JEI.removeAndHide(<galacticraftcore:basic_block_core:9>);
mods.jei.JEI.removeAndHide(<galacticraftcore:basic_block_core:11>);
mods.jei.JEI.removeAndHide(<galacticraftcore:basic_block_core:10>);
mods.jei.JEI.removeAndHide(<galacticraftcore:machine2:4>);
mods.jei.JEI.removeAndHide(<galacticraftplanets:mars_machine_t2>);
mods.jei.JEI.removeAndHide(<galacticraftcore:refinery>);
mods.jei.JEI.removeAndHide(<projectred-core:resource_item:102>);
mods.jei.JEI.removeAndHide(<projectred-core:resource_item:101>);
mods.jei.JEI.removeAndHide(<projectred-core:resource_item:100>);
mods.jei.JEI.removeAndHide(<projectred-core:resource_item:103>);
mods.jei.JEI.removeAndHide(<projectred-core:resource_item:251>);
mods.jei.JEI.removeAndHide(<forestry:resource_storage:3>);
mods.jei.JEI.removeAndHide(<forestry:resource_storage>);
mods.jei.JEI.removeAndHide(<forestry:resource_storage:1>);
mods.jei.JEI.removeAndHide(<forestry:resource_storage:2>);
mods.jei.JEI.removeAndHide(<forestry:resources:1>);
mods.jei.JEI.removeAndHide(<galacticraftcore:basic_block_core:5>);
mods.jei.JEI.removeAndHide(<forestry:resources:2>);
mods.jei.JEI.removeAndHide(<galacticraftcore:basic_block_core:6>);
mods.jei.JEI.removeAndHide(<appliedenergistics2:charged_quartz_ore>);
mods.jei.JEI.removeAndHide(<gregtech:meta_block_compressed_125:10>);
mods.jei.JEI.removeAndHide(<forestry:apatite>);
mods.jei.JEI.removeAndHide(<galacticraftcore:basic_block_core:8>);
mods.jei.JEI.removeAndHide(<galacticraftcore:basic_block_core:7>);
mods.jei.JEI.removeAndHide(<forestry:resources>);
mods.jei.JEI.removeAndHide(<appliedenergistics2:quartz_ore>);
mods.jei.JEI.removeAndHide(<galacticraftplanets:item_basic_asteroids:9>);
mods.jei.JEI.removeAndHide(<galacticraftplanets:item_basic_asteroids>);
mods.jei.JEI.removeAndHide(<galacticraftplanets:asteroids_block:7>);
mods.jei.JEI.removeAndHide(<appliedenergistics2:material:2>);
mods.jei.JEI.removeAndHide(<appliedenergistics2:material>);
mods.jei.JEI.removeAndHide(<bloodmagic:component:19>);
mods.jei.JEI.removeAndHide(<bloodmagic:component:20>);
mods.jei.JEI.removeAndHide(<bloodmagic:component:21>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ore:*>);
mods.jei.JEI.removeAndHide(<galacticraftcore:basic_item:11>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot:*>);
mods.jei.JEI.removeAndHide(<nuclearcraft:dust:*>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:7>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:6>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:5>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:4>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:2>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:3>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:1>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block>);
mods.jei.JEI.removeAndHide(<nuclearcraft:alloy>);
mods.jei.JEI.removeAndHide(<nuclearcraft:gem_dust:7>);
mods.jei.JEI.removeAndHide(<nuclearcraft:gem_dust:2>);
mods.jei.JEI.removeAndHide(<nuclearcraft:gem_dust:6>);
mods.jei.JEI.removeAndHide(<nuclearcraft:gem_dust>);
mods.jei.JEI.removeAndHide(<nuclearcraft:gem_dust:3>);
mods.jei.JEI.removeAndHide(<nuclearcraft:gem:6>);
mods.jei.JEI.removeAndHide(<nuclearcraft:alloy:5>);
mods.jei.JEI.removeAndHide(<nuclearcraft:compound:6>);
mods.jei.JEI.removeAndHide(<nuclearcraft:compound:7>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:13>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:12>);
mods.jei.JEI.removeAndHide(<galacticraftcore:machine2>);
mods.jei.JEI.removeAndHide(<galacticraftcore:machine:12>);
mods.jei.JEI.removeAndHide(<galacticraftcore:basic_item:13>);
mods.jei.JEI.removeAndHide(<galacticraftcore:basic_item:14>);
mods.jei.JEI.removeAndHide(<bloodmagic:component:23>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_ingot:*>);
mods.jei.JEI.removeAndHide(<forestry:charcoal>);
mods.jei.JEI.removeAndHide(<minecraft:coal_ore>);
mods.jei.JEI.removeAndHide(<minecraft:iron_ore>);
mods.jei.JEI.removeAndHide(<minecraft:gold_ore>);
mods.jei.JEI.removeAndHide(<minecraft:diamond_ore>);
mods.jei.JEI.removeAndHide(<minecraft:emerald_ore>);
mods.jei.JEI.removeAndHide(<minecraft:lapis_ore>);
mods.jei.JEI.removeAndHide(<minecraft:redstone_ore>);
mods.jei.JEI.removeAndHide(<minecraft:quartz_ore>);
mods.jei.JEI.removeAndHide(<biomesoplenty:gem_ore:*>);
mods.jei.JEI.removeAndHide(<harvestcraft:freshwateritem>);
mods.jei.JEI.removeAndHide(<enderio:item_material:31>);
mods.jei.JEI.removeAndHide(<enderio:item_material:30>);
mods.jei.JEI.removeAndHide(<enderio:item_material:29>);
mods.jei.JEI.removeAndHide(<enderio:item_material:27>);
mods.jei.JEI.removeAndHide(<enderio:item_material:26>);
mods.jei.JEI.removeAndHide(<enderio:item_material:25>);
mods.jei.JEI.removeAndHide(<enderio:item_material:23>);
mods.jei.JEI.removeAndHide(<enderio:item_material:24>);
mods.jei.JEI.removeAndHide(<artifacts:everlasting_clownfish>);
mods.jei.JEI.removeAndHide(<artifacts:everlasting_rabbit>);
mods.jei.JEI.removeAndHide(<artifacts:everlasting_spider_eye>);
mods.jei.JEI.removeAndHide(<artifacts:everlasting_rotten_flesh>);
mods.jei.JEI.removeAndHide(<artifacts:everlasting_cooked_chicken>);
mods.jei.JEI.removeAndHide(<artifacts:everlasting_chicken>);
mods.jei.JEI.removeAndHide(<artifacts:everlasting_cooked_beef>);
mods.jei.JEI.removeAndHide(<artifacts:everlasting_beef>);
mods.jei.JEI.removeAndHide(<artifacts:everlasting_cooked_porkchop>);
mods.jei.JEI.removeAndHide(<artifacts:everlasting_porkchop>);
mods.jei.JEI.removeAndHide(<artifacts:everlasting_clownfish>);
mods.jei.JEI.removeAndHide(<artifacts:everlasting_cooked_salmon>);
mods.jei.JEI.removeAndHide(<artifacts:everlasting_salmon>);
mods.jei.JEI.removeAndHide(<artifacts:everlasting_cooked_cod>);
mods.jei.JEI.removeAndHide(<artifacts:everlasting_cod>);
mods.jei.JEI.removeAndHide(<artifacts:everlasting_rabbit_stew>);
mods.jei.JEI.removeAndHide(<artifacts:everlasting_cooked_mutton>);
mods.jei.JEI.removeAndHide(<artifacts:everlasting_mutton>);
mods.jei.JEI.removeAndHide(<artifacts:everlasting_cooked_rabbit>);
mods.jei.JEI.removeAndHide(<enderio:item_material:32>);
mods.jei.JEI.removeAndHide(<enderio:item_material:33>);
mods.jei.JEI.removeAndHide(<extraplanets:tier11_items:5>);
mods.jei.JEI.removeAndHide(<extraplanets:tier8_items:5>);
mods.jei.JEI.removeAndHide(<extraplanets:tier5_items:7>);
mods.jei.JEI.removeAndHide(<extraplanets:tier5_items:5>);
mods.jei.JEI.removeAndHide(<extraplanets:tier10_items:5>);
mods.jei.JEI.removeAndHide(<extraplanets:tier4_items:5>);
mods.jei.JEI.removeAndHide(<extraplanets:ingot_lead>);
mods.jei.JEI.removeAndHide(<extraplanets:tier9_items:5>);
mods.jei.JEI.removeAndHide(<extraplanets:tier6_items:5>);
mods.jei.JEI.removeAndHide(<appliedenergistics2:inscriber>);
mods.jei.JEI.removeAndHide(<enderio:block_combustion_generator>);
mods.jei.JEI.removeAndHide(<enderio:block_enhanced_combustion_generator>);
mods.jei.JEI.removeAndHide(<projectred-core:resource_item:105>);
mods.jei.JEI.removeAndHide(<nuclearcraft:alloy_furnace>);
mods.jei.JEI.removeAndHide(<nuclearcraft:manufactory>);
mods.jei.JEI.removeAndHide(<nuclearcraft:chemical_reactor>);
mods.jei.JEI.removeAndHide(<nuclearcraft:rock_crusher>);
mods.jei.JEI.removeAndHide(<nuclearcraft:extractor>);
mods.jei.JEI.removeAndHide(<nuclearcraft:pressurizer>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_former>);
mods.jei.JEI.removeAndHide(<nuclearcraft:electrolyzer>);
mods.jei.JEI.removeAndHide(<nuclearcraft:supercooler>);
mods.jei.JEI.removeAndHide(<nuclearcraft:crystallizer>);
mods.jei.JEI.removeAndHide(<nuclearcraft:melter>);
mods.jei.JEI.removeAndHide(<nuclearcraft:enricher>);
mods.jei.JEI.removeAndHide(<nuclearcraft:nuclear_furnace>);
mods.jei.JEI.removeAndHide(<nuclearcraft:alloy:13>);
mods.jei.JEI.removeAndHide(<nuclearcraft:lithium_ion_cell>.withTag({energyStorage: {energy: 0 as long, capacity: 8000000 as long}}));
mods.jei.JEI.removeAndHide(<extraplanets:eris:6>);
mods.jei.JEI.removeAndHide(<extraplanets:pluto:6>);
mods.jei.JEI.removeAndHide(<extraplanets:neptune:10>);
mods.jei.JEI.removeAndHide(<extraplanets:neptune:3>);
mods.jei.JEI.removeAndHide(<extraplanets:saturn:5>);
mods.jei.JEI.removeAndHide(<extraplanets:jupiter:7>);
mods.jei.JEI.removeAndHide(<extraplanets:jupiter:3>);
mods.jei.JEI.removeAndHide(<extraplanets:ingot_mercury>);
mods.jei.JEI.removeAndHide(<extraplanets:ingot_uranium>);
mods.jei.JEI.removeAndHide(<extraplanets:eris:3>);
mods.jei.JEI.removeAndHide(<extraplanets:pluto:3>);
mods.jei.JEI.removeAndHide(<extraplanets:neptune:4>);
mods.jei.JEI.removeAndHide(<extraplanets:saturn:6>);
mods.jei.JEI.removeAndHide(<extraplanets:jupiter:11>);
mods.jei.JEI.removeAndHide(<extraplanets:jupiter:4>);
mods.jei.JEI.removeAndHide(<extraplanets:ceres:5>);
mods.jei.JEI.removeAndHide(<extraplanets:mercury:6>);
mods.jei.JEI.removeAndHide(<extraplanets:mercury:3>);
mods.jei.JEI.removeAndHide(<extraplanets:eris:4>);
mods.jei.JEI.removeAndHide(<extraplanets:pluto:4>);
mods.jei.JEI.removeAndHide(<extraplanets:neptune:6>);
mods.jei.JEI.removeAndHide(<extraplanets:uranus:7>);
mods.jei.JEI.removeAndHide(<extraplanets:saturn:3>);
mods.jei.JEI.removeAndHide(<extraplanets:jupiter:5>);
mods.jei.JEI.removeAndHide(<extraplanets:ceres:6>);
mods.jei.JEI.removeAndHide(<extraplanets:ceres:3>);
mods.jei.JEI.removeAndHide(<extraplanets:mercury:4>);
mods.jei.JEI.removeAndHide(<extraplanets:eris:5>);
mods.jei.JEI.removeAndHide(<extraplanets:pluto:5>);
mods.jei.JEI.removeAndHide(<extraplanets:neptune:5>);
mods.jei.JEI.removeAndHide(<extraplanets:uranus:3>);
mods.jei.JEI.removeAndHide(<extraplanets:saturn:4>);
mods.jei.JEI.removeAndHide(<extraplanets:jupiter:6>);
mods.jei.JEI.removeAndHide(<extraplanets:mercury:10>);
mods.jei.JEI.removeAndHide(<extraplanets:ceres:4>);
mods.jei.JEI.removeAndHide(<extraplanets:mercury:5>);
mods.jei.JEI.removeAndHide(<extraplanets:oberon:5>);
mods.jei.JEI.removeAndHide(<extraplanets:titan:4>);
mods.jei.JEI.removeAndHide(<extraplanets:rhea:3>);
mods.jei.JEI.removeAndHide(<extraplanets:callisto:5>);
mods.jei.JEI.removeAndHide(<extraplanets:triton:4>);
mods.jei.JEI.removeAndHide(<extraplanets:phobos:3>);
mods.jei.JEI.removeAndHide(<extraplanets:europa:5>);
mods.jei.JEI.removeAndHide(<extraplanets:kepler22b:9>);
mods.jei.JEI.removeAndHide(<extraplanets:kepler22b:5>);
mods.jei.JEI.removeAndHide(<extraplanets:titan:5>);
mods.jei.JEI.removeAndHide(<extraplanets:rhea:4>);
mods.jei.JEI.removeAndHide(<extraplanets:ganymede:3>);
mods.jei.JEI.removeAndHide(<extraplanets:triton:5>);
mods.jei.JEI.removeAndHide(<extraplanets:phobos:4>);
mods.jei.JEI.removeAndHide(<extraplanets:io:3>);
mods.jei.JEI.removeAndHide(<extraplanets:kepler22b:10>);
mods.jei.JEI.removeAndHide(<extraplanets:kepler22b:6>);
mods.jei.JEI.removeAndHide(<extraplanets:kepler22b:2>);
mods.jei.JEI.removeAndHide(<extraplanets:oberon:3>);
mods.jei.JEI.removeAndHide(<extraplanets:rhea:5>);
mods.jei.JEI.removeAndHide(<extraplanets:ganymede:4>);
mods.jei.JEI.removeAndHide(<extraplanets:callisto:3>);
mods.jei.JEI.removeAndHide(<extraplanets:phobos:5>);
mods.jei.JEI.removeAndHide(<extraplanets:io:4>);
mods.jei.JEI.removeAndHide(<extraplanets:europa:3>);
mods.jei.JEI.removeAndHide(<extraplanets:kepler22b:7>);
mods.jei.JEI.removeAndHide(<extraplanets:kepler22b:3>);
mods.jei.JEI.removeAndHide(<extraplanets:oberon:4>);
mods.jei.JEI.removeAndHide(<extraplanets:titan:3>);
mods.jei.JEI.removeAndHide(<extraplanets:ganymede:5>);
mods.jei.JEI.removeAndHide(<extraplanets:callisto:4>);
mods.jei.JEI.removeAndHide(<extraplanets:triton:3>);
mods.jei.JEI.removeAndHide(<extraplanets:io:5>);
mods.jei.JEI.removeAndHide(<extraplanets:europa:4>);
mods.jei.JEI.removeAndHide(<extraplanets:kepler22b:8>);
mods.jei.JEI.removeAndHide(<extraplanets:kepler22b:4>);
mods.jei.JEI.removeAndHide(<extraplanets:titania:5>);
mods.jei.JEI.removeAndHide(<extraplanets:titania:4>);
mods.jei.JEI.removeAndHide(<extraplanets:titania:3>);
mods.jei.JEI.removeAndHide(<extraplanets:iapetus:5>);
mods.jei.JEI.removeAndHide(<extraplanets:iapetus:4>);
mods.jei.JEI.removeAndHide(<extraplanets:iapetus:3>);
mods.jei.JEI.removeAndHide(<nuclearcraft:solar_panel_basic>);
mods.jei.JEI.removeAndHide(<nuclearcraft:solar_panel_advanced>);
mods.jei.JEI.removeAndHide(<nuclearcraft:solar_panel_du>);
mods.jei.JEI.removeAndHide(<nuclearcraft:solar_panel_elite>);
mods.jei.JEI.removeAndHide(<threng:machine:1>);
mods.jei.JEI.removeAndHide(<appliedenergistics2:material>);
mods.jei.JEI.removeAndHide(<threng:material:3>);
mods.jei.JEI.removeAndHide(<threng:machine:0>);
mods.jei.JEI.removeAndHide(<threng:machine:5>);
mods.jei.JEI.removeAndHide(<threng:material:2>);
mods.jei.JEI.removeAndHide(<nuclearcraft:cobblestone_generator>);
mods.jei.JEI.removeAndHide(<nuclearcraft:cobblestone_generator_compact>);
mods.jei.JEI.removeAndHide(<nuclearcraft:cobblestone_generator_dense>);
mods.jei.JEI.removeAndHide(<nuclearcraft:nitrogen_collector_dense>);
mods.jei.JEI.removeAndHide(<nuclearcraft:nitrogen_collector_compact>);
mods.jei.JEI.removeAndHide(<compactmachines3:fieldprojector>);
mods.jei.JEI.removeAndHide(<extraplanets:kepler22b:13>);
mods.jei.JEI.removeAndHide(<extraplanets:kepler22b:14>);
mods.jei.JEI.removeAndHide(<forestry:wood_pile>);
mods.jei.JEI.removeAndHide(<nuclearcraft:fission_dust:6>);
mods.jei.JEI.removeAndHide(<extraplanets:basic_crystallizer>);
mods.jei.JEI.removeAndHide(<enderio:block_zombie_generator>);
mods.jei.JEI.removeAndHide(<enderio:block_franken_zombie_generator>);
mods.jei.JEI.removeAndHide(<extraplanets:basic_smasher>);
mods.jei.JEI.removeAndHide(<extraplanets:basic_densifier>);
mods.jei.JEI.removeAndHide(<extraplanets:basic_purifier>);
mods.jei.JEI.removeAndHide(<enderio:block_ender_generator>);
mods.jei.JEI.removeAndHide(<extraplanets:basic_solar_evaporation_chamber>);
mods.jei.JEI.removeAndHide(<enderio:block_painter>);
mods.jei.JEI.removeAndHide(<enderio:block_stirling_generator>);
mods.jei.JEI.removeAndHide(<enderio:block_lava_generator>);
mods.jei.JEI.removeAndHide(<extraplanets:basic_chemical_injector>);
mods.jei.JEI.removeAndHide(<enderio:block_simple_stirling_generator>);
mods.jei.JEI.removeAndHide(<enderio:block_vat>);
mods.jei.JEI.removeAndHide(<forestry:carpenter>);
mods.jei.JEI.removeAndHide(<appliedenergistics2:material:16>);
mods.jei.JEI.removeAndHide(<appliedenergistics2:material:17>);
mods.jei.JEI.removeAndHide(<appliedenergistics2:material:18>);
mods.jei.JEI.removeAndHide(<avaritia:neutron_collector>);
mods.jei.JEI.removeAndHide(<avaritia:neutronium_compressor>);
mods.jei.JEI.removeAndHide(<enderio:block_enhanced_sag_mill>);
mods.jei.JEI.removeAndHide(<enderio:block_simple_sag_mill>);
mods.jei.JEI.removeAndHide(<enderio:block_sag_mill>);
mods.jei.JEI.removeAndHide(<nuclearcraft:manufactory>);
mods.jei.JEI.removeAndHide(<galacticraftcore:oil_canister_partial:1>);
mods.jei.JEI.removeAndHide(<galacticraftcore:fuel_canister_partial:1>);
mods.jei.JEI.removeAndHide(<galacticraftcore:oil_canister_partial:1001>);
mods.jei.JEI.removeAndHide(<galacticraftplanets:canister_partial_ln2:1>);
mods.jei.JEI.removeAndHide(<galacticraftplanets:canister_partial_lox:1>);
mods.jei.JEI.removeAndHide(<galacticraftplanets:methane_canister_partial:1>);
mods.jei.JEI.removeAndHide(<nuclearcraft:compound:5>);
mods.jei.JEI.removeAndHide(<nuclearcraft:voltaic_pile_basic>);
mods.jei.JEI.removeAndHide(<nuclearcraft:voltaic_pile_advanced>);
mods.jei.JEI.removeAndHide(<nuclearcraft:voltaic_pile_du>);
mods.jei.JEI.removeAndHide(<nuclearcraft:voltaic_pile_elite>);
mods.jei.JEI.removeAndHide(<nuclearcraft:lithium_ion_battery_basic>);
mods.jei.JEI.removeAndHide(<nuclearcraft:lithium_ion_battery_advanced>);
mods.jei.JEI.removeAndHide(<nuclearcraft:lithium_ion_battery_du>);
mods.jei.JEI.removeAndHide(<nuclearcraft:lithium_ion_battery_elite>);
mods.jei.JEI.removeAndHide(<nuclearcraft:salt_fission_controller>);
mods.jei.JEI.removeAndHide(<nuclearcraft:salt_fission_vessel>);
mods.jei.JEI.removeAndHide(<nuclearcraft:solid_fission_cell>);
mods.jei.JEI.removeAndHide(<nuclearcraft:solid_fission_controller>);
mods.jei.JEI.removeAndHide(<appliedenergistics2:grindstone>);
mods.jei.JEI.removeAndHide(<nuclearcraft:fluid_ethanol>);



var items as IItemStack[] = [
<extraplanets:massive_battery>.withTag({electricity: 500000.0 as float}),
<extraplanets:ultimate_battery>.withTag({electricity: 200000.0 as float}),
<extraplanets:zinc_battery>.withTag({electricity: 125000.0 as float}),
<extraplanets:advanced_battery>.withTag({electricity: 150000.0 as float}),
<extraplanets:nickel_battery>.withTag({electricity: 85000.0 as float}),
<extraplanets:mercury_battery>.withTag({electricity: 100000.0 as float}),
<extraplanets:solar:4>,
<extraplanets:solar>,
<enderio:block_solar_panel:4>,
<enderio:block_solar_panel:5>,
<enderio:block_solar_panel:6>,
<enderio:block_solar_panel>,
<forestry:bottler>,
<forestry:squeezer>,
<threng:machine:2>,
<qmd:ingot:12>,
<qmd:ingot:13>,
<qmd:ingot2:1>,
<qmd:ingot2>,
<qmd:ingot_alloy>,
<qmd:ingot_alloy:2>,
<qmd:ingot_alloy:3>,
<qmd:ingot_alloy:4>,
<qmd:ingot_alloy:5>,
<qmd:dust:6>,
<qmd:dust:7>,
<qmd:dust:8>,
<qmd:dust:9>,
<qmd:dust:10>,
<qmd:dust:11>,
<qmd:dust:12>,
<qmd:dust:13>,
<qmd:dust:14>,
<qmd:dust2>,
<qmd:dust2:1>,
<qmd:dust2:2>,
<qmd:dust2:3>,
<qmd:dust2:4>,
<qmd:dust2:5>,
<qmd:dust2:6>,
<qmd:ingot>,
<qmd:ingot:1>,
<qmd:ingot:3>,
<qmd:ingot:4>,
<appliedenergistics2:charger>,
<appliedenergistics2:quartz_growth_accelerator>,
<qmd:ingot:5>,
<qmd:ingot:6>,
<qmd:ingot:7>,
<qmd:ingot:8>,
<qmd:ingot:9>,
<gregtech:machine:2027>,
<qmd:ingot:10>,
<qmd:ingot:11>,
<qmd:dust>,
<qmd:dust:1>,
<qmd:dust:2>,
<qmd:dust:3>,
<avaritiaddons:infinity_compressor>,
<avaritia:neutronium_compressor>,
<qmd:dust:4>,
<qmd:dust:5>,
<qmd:chemical_dust:2>,
<qmd:chemical_dust:3>,
<qmd:chemical_dust:7>,
<threng:material:5>,
<qmd:atmosphere_collector>,
<threng:material:6>,
<forestry:still>,
<forestry:moistener>,
<forestry:fermenter>,
<extratrees:machine>,
<gregtech:meta_block_compressed_2010:4>,
<gregtech:meta_ingot:32048>,
<gregtech:meta_block_compressed_2003>,
<appliedenergistics2:material:4>,
<extraplanets:tier11_items:6>,
<enderio:item_material:21>

];

//循环移除
for i, item in items {
    mods.jei.JEI.removeAndHide(item);
}